apiVersion: messaging.knative.dev/v1
kind: InMemoryChannel
metadata:
  name: helloworld-go-ch
  # namespace: default
  # annotations:
    # eventing.knative.dev/scope: namespace
---
# Subscription from the InMemoryChannel to the Knative Service
apiVersion: messaging.knative.dev/v1
kind: Subscription
metadata:
  name: helloworld-go-sub
spec:
  channel:
    apiVersion: messaging.knative.dev/v1
    kind: InMemoryChannel
    name: helloworld-go-ch
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: helloworld-go